// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/google/wire"
	"loverrecipe/internal/controller"
	"loverrecipe/internal/ioc"
	"loverrecipe/internal/repository"
	"loverrecipe/internal/repository/dao"
	"loverrecipe/internal/services/dishes"
)

// Injectors from wire.go:

func InitHttpServer() *ioc.App {
	db := ioc.InitDB()
	dishesRepository := repository.NewDishesRepository(db)
	service := dishes.NewService(dishesRepository)
	dishController := controller.NewDishControllerWithRegister(service)
	component := ioc.InitHTTP(dishController)
	v := ioc.InitTasks()
	v2 := ioc.Crons()
	app := &ioc.App{
		HttpServer: component,
		Tasks:      v,
		Crons:      v2,
	}
	return app
}

// wire.go:

var (
	BaseSet   = wire.NewSet(ioc.InitDB, ioc.InitRedisCmd, ioc.InitRedisClient, ioc.InitIDGenerator)
	dishesSet = wire.NewSet(dao.NewDishesDao, repository.NewDishesRepository, dishes.NewService, controller.NewDishControllerWithRegister)
)
