// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/google/wire"
	"loverrecipe/internal/ioc"
)

// Injectors from wire.go:

func InitHttpServer() *ioc.App {
	component := ioc.InitHTTP()
	v := ioc.InitTasks()
	v2 := ioc.Crons()
	app := &ioc.App{
		HttpServer: component,
		Tasks:      v,
		Crons:      v2,
	}
	return app
}

// wire.go:

var (
	BaseSet = wire.NewSet(ioc.InitDB, ioc.InitRedisCmd, ioc.InitRedisClient, ioc.InitIDGenerator)
)
