// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/google/wire"
	"loverrecipe/internal/controller"
	"loverrecipe/internal/ioc"
	"loverrecipe/internal/repository"
	"loverrecipe/internal/repository/dao"
	"loverrecipe/internal/services/dishes"
	"loverrecipe/internal/services/user"
	"loverrecipe/internal/token"
)

// Injectors from wire.go:

func InitHttpServer() *ioc.App {
	db := ioc.InitDB()
	dishesRepository := repository.NewDishesRepository(db)
	service := dishes.NewService(dishesRepository)
	dishController := controller.NewDishControllerWithRegister(service)
	userDao := dao.NewUserDao(db)
	userRepository := repository.NewUserRepository(userDao)
	jwtTokenHandler := token.RegisterJwt()
	sonyflake := ioc.InitIDGenerator()
	userService := user.NewService(userRepository, jwtTokenHandler, sonyflake)
	userController := controller.NewUserController(userService)
	component := ioc.InitHTTP(dishController, userController)
	v := ioc.InitTasks()
	v2 := ioc.Crons()
	app := &ioc.App{
		HttpServer: component,
		Tasks:      v,
		Crons:      v2,
	}
	return app
}

// wire.go:

var (
	BaseSet   = wire.NewSet(ioc.InitDB, ioc.InitRedisCmd, ioc.InitRedisClient, ioc.InitIDGenerator, token.RegisterJwt)
	dishesSet = wire.NewSet(dao.NewDishesDao, repository.NewDishesRepository, dishes.NewService, controller.NewDishControllerWithRegister)
	userSet   = wire.NewSet(dao.NewUserDao, repository.NewUserRepository, user.NewService, controller.NewUserController)
)
