mysql:
  dsn: "root:root@tcp(localhost:13316)/notification?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=1s&readTimeout=3s&writeTimeout=3s&multiStatements=true&interpolateParams=true"

redis:
  addr: "localhost:6379"

server:
  http:
    host: "0.0.0.0"
    port: 9002


trace:
  zipkin:
    endpoint: "http://localhost:9411/api/v2/spans"
    serviceName: "lover-eat"

