basePath: /api/v1
definitions:
  dishes.DishesStatistics:
    properties:
      avg_calorie:
        type: integer
      avg_price:
        type: integer
      total_calorie:
        type: integer
      total_dishes:
        type: integer
      total_price:
        type: integer
    type: object
  domain.CreateDishesRequest:
    properties:
      calorie:
        minimum: 0
        type: integer
      desc:
        maxLength: 200
        type: string
      img:
        maxLength: 200
        type: string
      name:
        maxLength: 100
        minLength: 1
        type: string
      price:
        minimum: 0
        type: integer
      type:
        type: integer
      user_id:
        type: integer
    required:
    - name
    - type
    - user_id
    type: object
  domain.CreateUserInput:
    properties:
      avatar:
        type: string
      id:
        type: integer
      name:
        maxLength: 50
        minLength: 2
        type: string
      password:
        type: string
      status:
        enum:
        - 0
        - 1
        type: integer
    required:
    - name
    - password
    - status
    type: object
  domain.CreateUserOutput:
    properties:
      token:
        type: string
    type: object
  domain.Dishes:
    properties:
      calorie:
        type: integer
      ctime:
        type: integer
      desc:
        type: string
      id:
        type: integer
      img:
        type: string
      name:
        type: string
      price:
        type: integer
      type:
        type: integer
      user_id:
        type: integer
      utime:
        type: integer
    type: object
  domain.DishesListResponse:
    properties:
      list:
        items:
          $ref: '#/definitions/domain.DishesWithType'
        type: array
      page:
        type: integer
      size:
        type: integer
      total:
        type: integer
    type: object
  domain.DishesWithType:
    properties:
      calorie:
        type: integer
      ctime:
        type: integer
      desc:
        type: string
      id:
        type: integer
      img:
        type: string
      name:
        type: string
      price:
        type: integer
      type:
        type: integer
      type_color:
        type: string
      type_description:
        type: string
      type_icon:
        type: string
      type_name:
        type: string
      user_id:
        type: integer
      utime:
        type: integer
    type: object
  domain.UpdateDishesRequest:
    properties:
      calorie:
        minimum: 0
        type: integer
      desc:
        maxLength: 200
        type: string
      id:
        type: integer
      img:
        maxLength: 200
        type: string
      name:
        maxLength: 100
        minLength: 1
        type: string
      price:
        minimum: 0
        type: integer
      type:
        type: integer
      user_id:
        type: integer
    required:
    - id
    - name
    - type
    - user_id
    type: object
  response.Response:
    properties:
      code:
        description: 响应状态码
        example: 200
        type: integer
      data:
        description: 响应数据，可选
      msg:
        description: 响应消息
        example: success
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: 用户食谱管理系统的后端 API 服务
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: 用户食谱管理系统 API
  version: "1.0"
paths:
  /api/v1/dishes:
    get:
      consumes:
      - application/json
      description: 分页获取当前用户的菜品列表
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 页码，默认1
        in: query
        name: page
        type: integer
      - description: 每页数量，默认10，最大100
        in: query
        name: size
        type: integer
      - description: 菜品种类ID
        in: query
        name: type
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 获取成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/domain.DishesListResponse'
              type: object
        "400":
          description: 请求参数错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
        "401":
          description: 未授权
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
        "500":
          description: 服务器内部错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: 获取菜品列表
      tags:
      - 菜品管理
    post:
      consumes:
      - application/json
      description: 创建新的菜品
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 菜品信息
        in: body
        name: dishes
        required: true
        schema:
          $ref: '#/definitions/domain.CreateDishesRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 创建成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/domain.Dishes'
              type: object
        "400":
          description: 请求参数错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
        "401":
          description: 未授权
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
        "500":
          description: 服务器内部错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: 创建菜品
      tags:
      - 菜品管理
  /api/v1/dishes/{id}:
    delete:
      consumes:
      - application/json
      description: 删除指定菜品
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 菜品ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 删除成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
        "400":
          description: 请求参数错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
        "401":
          description: 未授权
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
        "403":
          description: 无权限
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
        "404":
          description: 菜品不存在
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
        "500":
          description: 服务器内部错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: 删除菜品
      tags:
      - 菜品管理
    get:
      consumes:
      - application/json
      description: 根据菜品ID获取菜品详细信息
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 菜品ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 获取成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/domain.Dishes'
              type: object
        "400":
          description: 请求参数错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
        "404":
          description: 菜品不存在
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
        "500":
          description: 服务器内部错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: 获取菜品详情
      tags:
      - 菜品管理
    put:
      consumes:
      - application/json
      description: 更新菜品信息
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 菜品ID
        in: path
        name: id
        required: true
        type: integer
      - description: 菜品更新信息
        in: body
        name: dishes
        required: true
        schema:
          $ref: '#/definitions/domain.UpdateDishesRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 更新成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/domain.Dishes'
              type: object
        "400":
          description: 请求参数错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
        "401":
          description: 未授权
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
        "404":
          description: 菜品不存在
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
        "500":
          description: 服务器内部错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: 更新菜品
      tags:
      - 菜品管理
  /api/v1/dishes/search:
    get:
      consumes:
      - application/json
      description: 根据关键词搜索菜品
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 搜索关键词
        in: query
        name: keyword
        required: true
        type: string
      - description: 页码，默认1
        in: query
        name: page
        type: integer
      - description: 每页数量，默认10，最大100
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 搜索成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/domain.DishesListResponse'
              type: object
        "400":
          description: 请求参数错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
        "401":
          description: 未授权
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
        "500":
          description: 服务器内部错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: 搜索菜品
      tags:
      - 菜品管理
  /api/v1/dishes/statistics:
    get:
      consumes:
      - application/json
      description: 获取当前用户的菜品统计信息
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 获取成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/dishes.DishesStatistics'
              type: object
        "401":
          description: 未授权
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
        "500":
          description: 服务器内部错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: 获取菜品统计
      tags:
      - 菜品管理
  /api/v1/dishes/type/{typeId}:
    get:
      consumes:
      - application/json
      description: 根据菜品种类ID获取菜品列表
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 菜品种类ID
        in: path
        name: typeId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 获取成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/domain.Dishes'
                  type: array
              type: object
        "400":
          description: 请求参数错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
        "401":
          description: 未授权
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
        "500":
          description: 服务器内部错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: 按种类获取菜品
      tags:
      - 菜品管理
  /api/v1/dishes/with-type:
    get:
      consumes:
      - application/json
      description: 获取当前用户的菜品列表，包含种类详细信息
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 获取成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/domain.DishesWithType'
                  type: array
              type: object
        "401":
          description: 未授权
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
        "500":
          description: 服务器内部错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: 获取带种类信息的菜品
      tags:
      - 菜品管理
  /api/v1/user/register:
    post:
      consumes:
      - application/json
      description: 处理用户注册请求，验证输入参数并创建新用户
      parameters:
      - description: 用户注册信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/domain.CreateUserInput'
      produces:
      - application/json
      responses:
        "200":
          description: 注册成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/domain.CreateUserOutput'
              type: object
        "400":
          description: 请求参数错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
        "500":
          description: 服务器内部错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: 用户注册
      tags:
      - 用户管理
securityDefinitions:
  BearerAuth:
    description: 请输入 "Bearer " 加上 JWT token
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
